---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: domains.datumapis.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: datumapis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                registrarIANAID:
                  type: string
                createdDate:
                  type: string
                modifiedDate:
                  type: string
                nameservers:
                  type: string
                DNSSEC:
                  type: string
                statusFlags:
                  type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: domains
    # singular name to be used as an alias on the CLI and for display
    singular: domain
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Domain
    # shortNames allow shorter string to match your resource on the CLI
    # shortNames:
    # - ct

---
apiVersion: "domains.datumapis.com/v1alpha"
kind: Domain
metadata:
  name: example.com
spec:
  name: example.com
