name: Enhancement Tracking Issue
description: Provide supporting details for an enhancement to the Datum Cloud Platform.
labels:
- enhancement
type: Enhancement
body:
  - type: textarea
    attributes:
      label: "High-Level Summary"
      description: |
        Provide a concise overview of the proposed enhancement.
      placeholder: "Brief description of what this enhancement aims to accomplish."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Motivation"
      description: |
        Explain why this enhancement is needed. What problem does it solve or opportunity does it address?
      placeholder: "Describe the current pain points, limitations, or opportunities that drive this enhancement."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Goals"
      description: |
        What specific outcomes do you want to achieve with this enhancement?
      placeholder: "List the key objectives and success criteria for this enhancement."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Non-Goals"
      description: |
        What is explicitly out of scope for this enhancement?
      placeholder: "Clarify what this enhancement will NOT address to set clear boundaries."
    validations:
      required: false
